name: check

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  Check:
    name: ShellCheck
    runs-on: ubuntu-latest
    steps:
    - name: Check out code into directory
      uses: actions/checkout@v1

    - name: ShellCheck version
      run: shellcheck --version

    - name: Run ShellCheck for 'sh'
      run: make check-sh

    - name: Run ShellCheck for 'bash'
      run: make check-bash

    - name: Run ShellCheck for 'dash'
      run: make check-dash

    - name: Run ShellCheck for 'ksh'
      run: make check-ksh
